import Link from 'next/link';
import styles from '@/styles/Home.module.css';

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export default function Footer() {
  return (
    <div className={styles.aboutArticle + ' ' + inter.className}>
      <p className={styles.aboutParagraph}>
        Kiwipedia is an experimental app that uses AI to generate an entirely
        synthetic encyclopedia.
      </p>
      <p className={styles.aboutParagraph}>
        As more content and is generated by AI, Kiwipedia gives a sense of what
        it feels like to navigate an environment where the provenance of
        everything is uncertain.
      </p>
      <p className={styles.aboutQuote}>
        “I'm not crazy, my reality is just different from yours.”
      </p>
      <p className={styles.aboutQuoteAttribution}>
        - the Cheshire Cat, in Lewis Carrol's <i>Alice in Wonderland</i> and{' '}
        <i>Through the Looking Glass</i>
      </p>
      <p className={styles.aboutAuthor}>
        Kiwipedia was created by Andy Coenen (
        <a
          href="https://www.cannoneyed.com"
          target="_blank"
          className={styles.link}
        >
          cannoneyed
        </a>
        ), a senior software engineer at Google Brain working AI
        controllability.{' '}
      </p>
    </div>
  );
}
