import { system } from './system.mjs';

export async function generateStableDiffusionPrompt(title) {
  // From https://gist.github.com/bluelovers/92dac6fe7dcbafd7b5ae0557e638e6ef
  const promptText = `Stable Diffusion is an AI art generation model similar to DALLE-2.
Here are some prompts for generating art with Stable Diffusion. 

Example:

- portrait of a homer simpson archer shooting arrow at forest monster, front game card, drark, marvel comics, dark, intricate, highly detailed, smooth, artstation, digital illustration
- pirate, concept art, deep focus, fantasy, intricate, highly detailed, digital painting, artstation, matte, sharp focus, illustration
- ghost inside a hunted room, art by lois van baarle and loish and ross tran and rossdraws and sam yang and samdoesarts and artgerm, digital art, highly detailed, intricate, sharp focus, Trending on Artstation HQ, deviantart, unreal engine 5, 4K UHD image
- red dead redemption 2, cinematic view, epic sky, detailed, concept art, low angle, high detail, warm lighting, volumetric, godrays, vivid, beautiful, trending on artstation
- a fantasy style portrait painting of rachel lane / alison brie hybrid in the style of francois boucher oil painting unreal 5 daz. rpg portrait, extremely detailed artgerm
- athena, greek goddess, claudia black, art by artgerm and greg rutkowski and magali villeneuve, bronze greek armor, owl crown, d & d, fantasy, intricate, portrait, highly detailed, headshot, digital painting, trending on artstation, concept art, sharp focus, illustration
- closeup portrait shot of a large strong female biomechanic woman in a scenic scifi environment, intricate, elegant, highly detailed, centered, digital painting, artstation, concept art, smooth, sharp focus, warframe, illustration
- ultra realistic illustration of steve urkle as the hulk, intricate, elegant, highly detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration
- portrait of beautiful happy young ana de armas, ethereal, realistic anime, trending on pixiv, detailed, clean lines, sharp lines, crisp lines, award winning illustration, masterpiece, 4k, eugene de blaas and ross tran, vibrant color scheme, intricately detailed
- A highly detailed and hyper realistic portrait of a gorgeous young ana de armas, lisa frank, trending on artstation, butterflies, floral, sharp focus, studio photo, intricate details, highly detailed, alberto seveso and geo2099 style

Prompts should be written in English, excluding the artist name, and include the following rule:

- Follow the structure of the example prompts. This means Write a description of the scene, followed by modifiers divided by commas to alter the mood, style, lighting, and more, excluding the artist name, separated by commas. place a extra commas. and place the extra Chinese translation for prompt at the end of each prompt. Finally, avoid at all costs making NSFW or offensive prompts. Be safe! If the image is of an NSFW subject, such as "Sex", try to make a prompt for an image of a more abstract and PG idea, like "Man & Woman".

Please write a prompt for Stable Diffusion to generate a cover image for the article for "${title}" in the english version of Wikipedia:`;
  const text = await system.getCompletion(promptText);
  return text;
}

export async function generateCaption(title, stableDiffusionPrompt) {
  const promptText = `Stable Diffusion is an AI art generation model similar to DALLE-2.
Here's a description of an image generated by stable Diffusion for the article for "${title}" in the english version of Wikipedia:

${stableDiffusionPrompt}

Please write a very short caption for the image in the article for "${title}" in the english version of Wikipedia:`;
  const text = await system.getCompletion(promptText);
  return text;
}

export async function generateImage(title) {
  const stableDiffusionPrompt = await generateStableDiffusionPrompt(title);
  const imageUrl = await system.generateImage(stableDiffusionPrompt);
  return imageUrl;
}
